name: ivykids_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_picker: ^0.8.7+3
  json_annotation: ^4.8.0
  lottie: ^2.3.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
